[SPDM] Update Emulator SPDM stack to support message handling though DOE and MCTP transports (#273)
* add doe stack on the emulator

* add workflow for DOE and publish artifacts for transaction analysis.

* transcript append bug fix for doe and some bug fixes in DOE transpport

---------

Co-authored-by: Parvathi Bhogaraju <pbhogaraju@microsoft.com>

diff --git a/.github/workflows/spdm-validator.yml b/.github/workflows/spdm-validator.yml
--- a/.github/workflows/spdm-validator.yml
+++ b/.github/workflows/spdm-validator.yml
@@ -94,17 +94,44 @@ jobs:
           popd
           popd
 
-      - name: Run SPDM validator test tests
+      - name: Run SPDM validator test tests on MCTP transport
         run: |
           export SPDM_VALIDATOR_DIR=$GITHUB_WORKSPACE/spdm-emu/build/bin
-          cargo t -p tests-integration -- --test test_spdm_validator --nocapture  --include-ignored
+          cargo t -p tests-integration -- --test test_mctp_spdm_responder_conformance --nocapture  --include-ignored
           sccache --show-stats
-
-      - name: Display SPDM Validator test results
+    
+      - name: Display SPDM Validator test results on MCTP transport
         run: |
           cat $GITHUB_WORKSPACE/test.log
       
       - name: Check for test failures
+        run: |
+          if grep -E 'test suite \(.*\) - pass: [0-9]+, fail: [1-9][0-9]*' $GITHUB_WORKSPACE/test.log; then
+            echo "Test suite had failures."
+            exit 1
+          fi
+
+      - name: Run SPDM validator test tests on DOE transport
+        run: |
+          export SPDM_VALIDATOR_DIR=$GITHUB_WORKSPACE/spdm-emu/build/bin
+          cargo t -p tests-integration -- --test test_doe_spdm_responder_conformance --nocapture  --include-ignored
+          sccache --show-stats
+
+      - name: Upload logs and traces
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: spdm-doe-validator-test-results
+          path: |
+            test.log
+            caliptra_spdm_validator.pcap
+            spdm_device_validator_output.txt
+
+      - name: Display SPDM Validator test results on DOE transport
+        run: |
+          cat $GITHUB_WORKSPACE/test.log
+
+      - name: Check for test failures on DOE transport
         run: |
           if grep -E 'test suite \(.*\) - pass: [0-9]+, fail: [1-9][0-9]*' $GITHUB_WORKSPACE/test.log; then
             echo "Test suite had failures."
