pcr quote fix and spdm validator tool improvement (#264)
Co-authored-by: Parvathi Bhogaraju <pbhogaraju@microsoft.com>

diff --git a/.github/workflows/spdm-validator.yml b/.github/workflows/spdm-validator.yml
--- a/.github/workflows/spdm-validator.yml
+++ b/.github/workflows/spdm-validator.yml
@@ -103,3 +103,10 @@ jobs:
       - name: Display SPDM Validator test results
         run: |
           cat $GITHUB_WORKSPACE/test.log
+      
+      - name: Check for test failures
+        run: |
+          if grep -E 'test suite \(.*\) - pass: [0-9]+, fail: [1-9][0-9]*' $GITHUB_WORKSPACE/test.log; then
+            echo "Test suite had failures."
+            exit 1
+          fi
